name: Build Incus Container with custom debian image

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-upload:
    uses: initiateit/navidrome_incus/.github/workflows/debian_minimal.yaml@main  # Reference the reusable workflow
    
  container-steps:
    needs: build-and-upload  # Ensure this job waits for 'build-and-upload' to finish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout repository first

      - name: Set up Incus
        uses: bdx0/action-incus@v1
        with:
          incus_version: latest  # Specify the version if you want a specific one

      - name: Download the image artifact
        uses: actions/download-artifact@v4
        with:
          name: debian-minimal-image
          
      - name: Download the image artifact
        uses: actions/download-artifact@v4
        with:
          name: metadata

      - name: Extract the image and metadata
        run: |
          sudo tar -xzvf debian-minimal-image.tar.gz
          ls -l debian-minimal-image
          
          sudo tar -xzvf metadata.tar.gz
          ls -l metadata.yaml

      - name: Import debootstrap image to Incus
        run: |
          # Import the debootstrap image to Incus
          sudo incus image import metadata.tar.gz debian-minimal-image.tar.gz --alias debian-minimal-image

      - name: Launch Debian Bookworm (12) Minimal container
        run: |
          sudo incus launch debian-minimal-image navidrome-incus
          
      - name: Export Incus container as an image
        run: |
          sudo incus publish navidrome-incus --alias navidrome-incus-image
          sudo incus image export navidrome-incus-image /home/runner/work/navidrome-incus-image

      - name: Verify Image Export
        run: |
          ls -lh /home/runner/work/

      - name: Upload Incus container image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: navidrome-incus-image
          path: /home/runner/work/navidrome-incus-image.tar.gz
          if-no-files-found: error
