name: Build Incus Container with FFmpeg and Navidrome

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Incus
        uses: bdx0/action-incus@v1
        with:
          incus_version: latest  # Specify the version if you want a specific one

      - name: Launch Debian Bookworm (12) Minimal container
        run: |
          sudo incus launch images:debian/12 navidrome-lxc

      - name: Export Incus container as an image
        run: |
          sudo incus publish navidrome-incus --alias navidrome-incus-image
          sudo incus image export navidrome-incus-image /home/runner/work/navidrome-incus-image

      - name: Verify Image Export
        run: |
          ls -lh /home/runner/work/

      - name: Upload Incus container image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: navidrome-lxc-image
          path: /home/runner/work/navidrome-incus-image.tar.gz
          if-no-files-found: error
