name: Build FFmpeg and Navidrome Binaries

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools and libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget build-essential automake autoconf libtool pkg-config \
            libopus-dev libmp3lame-dev libvorbis-dev openssl libssl-dev libtag1-dev zlib1g-dev nasm yasm

          
      - name: Download and install latest Go package
        run: |
          

          cd /home/runner/
          GO_VERSION=$(curl -s https://go.dev/VERSION?m=text | head -n 1)
          GO_TAR_URL="https://go.dev/dl/${GO_VERSION}.linux-amd64.tar.gz"
          curl -LO ${GO_TAR_URL}
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf ${GO_VERSION}.linux-amd64.tar.gz
          rm ${GO_VERSION}.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin

      - name: Download and install Node.js 22+
        run: |
          sudo apt-get remove -y nodejs
          sudo apt-get autoremove -y
          sudo rm -rf /usr/local/bin/node /usr/local/bin/npm /usr/local/lib/node_modules
          mkdir -p /home/runner/node
          cd /home/runner/node
          # installs nvm (Node Version Manager)
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          # download and install Node.js (you may need to restart the terminal)
          nvm install 22
          # verifies the right Node.js version is in the environment
          node -v # should print `v20.17.0`
          # verifies the right npm version is in the environment
          npm -v # should print `10.8.2`

      - name: Download Navidrome sources and compile
        run: |
          cd /home/runner
          git clone https://github.com/navidrome/navidrome
          cd navidrome
          make setup        # Install build dependencies
          make build        # Build UI and server, generates a single executable
